### ISSUE TITLE
VS2012 issue

### ISSUE THREAD

**Issue by hodiizidor** [giacomodrago/minijson_writer#7]
As VS2012 lacks complete support for c++, and only missing function involved in minijson_writer is std::isinfinite, there is workaround which could be included in code.

from 
`
#define MJW_CPP11_SUPPORTED __cplusplus > 199711L || _MSC_VER >= 1800
`
to 
`#define MJW_CPP11_SUPPORTED __cplusplus > 199711L || _MSC_VER >= 1700`

`#if _MSC_VER == 1700`
`namespace std {`
`	template<typename T> bool isfinite(T t)	{`
`		return t == t && t != std::numeric_limits<T>::infinity() &&	t != std::numeric_limits<T>::infinity();`
`	}`
`}`
`#endif`

**Comment by giacomodrago** [comment]
Well... I think VS2012 can be considered a legacy toolchain and if you have Boost you can probably just compile the code as it is, can't you? Sorry, I don't think it's worth it to mess with those already ugly macros and re-implement a basic Boost/standard library function for supporting VS2012, considering that it will soon disappear (I hope), I have no way to support it in the long run (I'm not going to install it), and you already have the workaround.
